spring:
  application:
    name: Security-3-Token
    datasource:
      url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: sang1411

jwt:
  issuer: test@naver.com
  secret_key: EtBXYf9LC58LKVW8fHyy2hjrDz3mSFjaJSH87O+sY4L/TmruLfeO3f0Wrm4vrl2pVAGrSNdGNg5BMHFQxREG2A==
  access-token-validity: 2h
  refresh-token-validity: 7d
