spring:
  application:
    name: Board-1-SignUp
  datasource:
    url: jdbc:mysql://localhost:3306/java_basic_signup?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true